### PR TITLE
Bellota ready for Google Fonts

### PR DESCRIPTION
**Pull request by yanone**
Hello,

I've been commissioned to update Bellota so it can be added to the Google Fonts library.
Please accept this PR to proceed.

Thank you

### CODE REVIEW

**Comment by kemie** [comment]
Hi @yanone ! I've been working a lot on Bellota the last few weeks and was about to push a new version with LOTS of changes and improvements- I'm unsure how to proceed now, as there probably will be conflicts between our versions.

**Comment by yanone** [comment]
I propose that you push your version. The changes I made are easy to replicate. Maybe you could let me know when you're done.

**Comment by kemie** [comment]
@yanone updated now. notable changes are:
-text variant
-Italics are now generated from the same master
-I remembered to close my tabs 😄

**Comment by yanone** [comment]
@kemie
Thank you. I'm deleting this PR and will submit a new one when I'm ready.

**Pull request closed without merging**
