### PR TITLE
Updated Bellota to Google Fonts specs

### PR DESCRIPTION
**Pull request by yanone**
Hi,
I was commissioned to prepare Bellota to meet Google Fonts specifications.
If you merge this PR, we can proceed with uploading the fonts.
Thank you

### CODE REVIEW

**Comment by kemie** [comment]
All done. Yay!

-- 
Kemie Guaida
www.monolinea.com

On 16 January 2020 at 14:38:42, Yanone (notifications@github.com) wrote:

Hi,
I was commissioned to prepare Bellota to meet Google Fonts specifications.
If you merge this PR, we can proceed with uploading the fonts.
Thank you
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/kemie/Bellota-Font/pull/5
Commit Summary

   - Changed nbspace width to space width
   - Updated to GF specs
   - Update Bellota.glyphs
   - Added partial build script
   - Added fresh TTFs
   - Bumped version string and date
   - Added authors and contributors file
   - Updated readme
   - Updated readme
   - Added final TTFs

File Changes

   - *M* OFL.txt <https://github.com/kemie/Bellota-Font/pull/5/files#diff-0>
   (106)
   - *A* authors.txt
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-1> (8)
   - *A* build.sh
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-2> (20)
   - *A* contributors.txt
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-3> (12)
   - *M* readme.md
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-4> (7)
   - *M* src/Bellota.glyphs
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-5> (2548)
   - *M* ttf/Bellota-Bold.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-6> (0)
   - *M* ttf/Bellota-BoldItalic.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-7> (0)
   - *M* ttf/Bellota-Italic.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-8> (0)
   - *M* ttf/Bellota-Light.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-9> (0)
   - *M* ttf/Bellota-LightItalic.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-10> (0)
   - *M* ttf/Bellota-Regular.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-11> (0)
   - *M* ttf/BellotaText-Bold.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-12> (0)
   - *M* ttf/BellotaText-BoldItalic.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-13> (0)
   - *M* ttf/BellotaText-Italic.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-14> (0)
   - *M* ttf/BellotaText-Light.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-15> (0)
   - *M* ttf/BellotaText-LightItalic.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-16> (0)
   - *M* ttf/BellotaText-Regular.ttf
   <https://github.com/kemie/Bellota-Font/pull/5/files#diff-17> (0)

Patch Links:

   - https://github.com/kemie/Bellota-Font/pull/5.patch
   - https://github.com/kemie/Bellota-Font/pull/5.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kemie/Bellota-Font/pull/5?email_source=notifications&email_token=AAOKPT6AYVZNEBLABB6YPX3Q6BPOFA5CNFSM4KHUE4OKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGUXVTA>,
or unsubscribe

**Comment by kemie** [comment]
Hey, since you seem to be more in the loop about this, do I need to do anything wrt the GF repository? pull requests and stuff like that? Or is it just a matter of time till it gets added?

**Comment by yanone** [comment]
It’s a matter of time, but once I submit the fonts (which I have) it’s out of my hands and view, so I can’t help with details.



> Am 19.02.2020 um 14:46 schrieb Kemie <notifications@github.com>:
> 
> Hey, since you seem to be more in the loop about this, do I need to do anything wrt the GF repository? pull requests and stuff like that? Or is it just a matter of time till it gets added?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



--

Yanone
Dipl.-Designer,
Master of Design in Type & Media
https://yanone.de
Twitter/Instagram: @yanone
+49 176 24023268 (Germany)

Type.World project:
https://type.world

Crowd funding on:
https://www.patreon.com/typeWorld

**Comment by kemie** [comment]
Perfect, thank you. Don't mind waiting, just wanted to know if I needed to
do anything. Thanks for all the help!

On 19 February 2020 at 14:57:13, Yanone (notifications@github.com) wrote:

It’s a matter of time, but once I submit the fonts (which I have) it’s out
of my hands and view, so I can’t help with details.



> Am 19.02.2020 um 14:46 schrieb Kemie <notifications@github.com>:
>
> Hey, since you seem to be more in the loop about this, do I need to do
anything wrt the GF repository? pull requests and stuff like that? Or is it
just a matter of time till it gets added?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>



--

Yanone
Dipl.-Designer,
Master of Design in Type & Media
https://yanone.de
Twitter/Instagram: @yanone
+49 176 24023268 (Germany)

Type.World project:
https://type.world

Crowd funding on:
https://www.patreon.com/typeWorld


—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/kemie/Bellota-Font/pull/5?email_source=notifications&email_token=AAOKPT3GZMNPHXGXJ65GQWLRDU3DTA5CNFSM4KHUE4OKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMH6JFI#issuecomment-588244117>,
or unsubscribe

**Pull request merged**
